- name: Software Installation on Mastercontroller ( localhost )
  become: true
  hosts: localhost
  connection: local
  tasks:
    - name: Executing on local
      script: Jenkins.sh
- name: Copy and Execute Script
  hosts: K8master
  become: true  # Enable privilege escalation to execute commands as root
  tasks:
    - name: download K8Script from Github
      get_url: 
        url: https://raw.githubusercontent.com/amelkalidas/CICD2/main/K8master.sh
        dest: /home/ubuntu/
        mode: '+x'
    - name: install docker from script
      script: /home/ubuntu/K8master.sh

- name: Copy and Execute Script
  hosts: K8Node
  become: true  # Enable privilege escalation to execute commands as root
  tasks:
    - name: download K8Script from Github
      get_url: 
        url: https://github.com/amelkalidas/CICD2/blob/main/K8nodes.sh
        dest: /home/ubuntu/
        mode: '+x'
    - name: install docker from script
      script: /home/ubuntu/K8nodes.sh
        
      